### ISSUE TITLE
 [Feature Request] Add CA and RA to mod switch availability

### ISSUE THREAD

**Issue by timbergeron** [quakeone/CRx#31]

**Comment by inf1niti** [comment]
CA and RA would be awesome to add to the server, but I also worry about too many very different mods/pieces trying to coexist in one codebase.   Obviously KTX is a good example of doing this successfully - but I still think there is the risk of introducing bugs due to added complexity.

I think we should weight whether this is the best way to do this, or if it would be easier to add CA / RA as a separate server mod.

Either way, updating/modernizing CAx/RA and getting them running on QSS/FTE/QE servers is 1000% worthwhile 👍

**Comment by timbergeron** [comment]
It would depend on how difficult the server switch coding is I think

**Comment by buckshot41** [comment]
Well, what was the goal when combining ctf and tdm?  There are definitely benefits to sharing a codebase, but any additional mode adds complexity and probably requires some refactoring and retesting things.  But pulling a bunch of logic out of this mod and into another one probably won't be any better.
I was already trying to get CAx into my QE mod, so I'm interested in trying to accomplish this and there is definitely interest on the QE side.  It just came up again last night.  I'm probably going to take care of some of the quick fixes or higher priority items first then take a stab at this.

**Comment by inf1niti** [comment]
sounds good :) 

Yeah I agree, all in one is best.  With CTF & DM they're both CRMOD though, so they have the same menus and stuff.  

CA & RA have very different menu systems, so we would need to think about how to integrate those.  It might make sense to move a lot of it over into a single system though, IDK.  

Anyway I agree with you, just want to think through the details a bit in case we run into any challenges along the way 🙂
